/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_nativeimp_util_DataPacket */

#ifndef _Included_agentj_nativeimp_util_DataPacket
#define _Included_agentj_nativeimp_util_DataPacket
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
