/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_nativeimp_NsDatagramSocketImpl */

#ifndef _Included_agentj_nativeimp_NsDatagramSocketImpl
#define _Included_agentj_nativeimp_NsDatagramSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    peek
 * Signature: (Ljava/lang/Long;)I
 */
JNIEXPORT jint JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_peek
  (JNIEnv *, jobject, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    peekData
 * Signature: (Lagentj/nativeimp/util/DataPacket;)I
 */
JNIEXPORT jint JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_peekData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    join
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_join
  (JNIEnv *, jobject, jlong);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    leave
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_leave
  (JNIEnv *, jobject, jlong);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    datagramSocketClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_datagramSocketClose
  (JNIEnv *, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    socketSetOption
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_socketSetOption
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    socketGetOption
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_socketGetOption
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    disconnect0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_disconnect0
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_init
  (JNIEnv *, jclass);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    send0
 * Signature: (Lagentj/nativeimp/util/DataPacket;)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_send0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    receive0
 * Signature: (Lagentj/nativeimp/util/DataPacket;)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_receive0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    datagramSocketCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_datagramSocketCreate
  (JNIEnv *, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    bind0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_bind0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    connect0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_connect0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    setTimeToLive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_setTimeToLive
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    getTimeToLive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_getTimeToLive
  (JNIEnv *, jobject);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    setTTL
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_setTTL
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     agentj_nativeimp_NsDatagramSocketImpl
 * Method:    getTTL
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_agentj_nativeimp_NsDatagramSocketImpl_getTTL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
