/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_nativeimp_SocketOutputStream */

#ifndef _Included_agentj_nativeimp_SocketOutputStream
#define _Included_agentj_nativeimp_SocketOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agentj_nativeimp_SocketOutputStream
 * Method:    socketWrite0
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_SocketOutputStream_socketWrite0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     agentj_nativeimp_SocketOutputStream
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_SocketOutputStream_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
