/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_nativeimp_NsSocketImpl */

#ifndef _Included_agentj_nativeimp_NsSocketImpl
#define _Included_agentj_nativeimp_NsSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef agentj_nativeimp_NsSocketImpl_SHUT_RD
#define agentj_nativeimp_NsSocketImpl_SHUT_RD 0L
#undef agentj_nativeimp_NsSocketImpl_SHUT_WR
#define agentj_nativeimp_NsSocketImpl_SHUT_WR 1L
/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketCreate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketCreate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketConnect
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketConnect
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketBind
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketBind
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketListen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketListen
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketAccept
 * Signature: (Ljava/net/SocketImpl;)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketAccept
  (JNIEnv *, jobject, jobject);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_agentj_nativeimp_NsSocketImpl_socketAvailable
  (JNIEnv *, jobject);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketClose0
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketClose0
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketShutdown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketShutdown
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    initProto
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_initProto
  (JNIEnv *, jclass);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketSetOption
 * Signature: (IZLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketSetOption
  (JNIEnv *, jobject, jint, jboolean, jobject);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketGetOption
 * Signature: (ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_agentj_nativeimp_NsSocketImpl_socketGetOption
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     agentj_nativeimp_NsSocketImpl
 * Method:    socketSendUrgentData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_NsSocketImpl_socketSendUrgentData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
