/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_nativeimp_NsSocketImpl_WaitForConnectComplete */

#ifndef _Included_agentj_nativeimp_NsSocketImpl_WaitForConnectComplete
#define _Included_agentj_nativeimp_NsSocketImpl_WaitForConnectComplete
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
