/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_nativeimp_SocketInputStream */

#ifndef _Included_agentj_nativeimp_SocketInputStream
#define _Included_agentj_nativeimp_SocketInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef agentj_nativeimp_SocketInputStream_SKIP_BUFFER_SIZE
#define agentj_nativeimp_SocketInputStream_SKIP_BUFFER_SIZE 2048L
/*
 * Class:     agentj_nativeimp_SocketInputStream
 * Method:    socketRead0
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_agentj_nativeimp_SocketInputStream_socketRead0
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     agentj_nativeimp_SocketInputStream
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_SocketInputStream_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
