/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_nativeimp_ProtolibTimer */

#ifndef _Included_agentj_nativeimp_ProtolibTimer
#define _Included_agentj_nativeimp_ProtolibTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agentj_nativeimp_ProtolibTimer
 * Method:    createNativeTimer
 * Signature: (DI)V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_ProtolibTimer_createNativeTimer
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     agentj_nativeimp_ProtolibTimer
 * Method:    startNativeTimer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_ProtolibTimer_startNativeTimer
  (JNIEnv *, jobject);

/*
 * Class:     agentj_nativeimp_ProtolibTimer
 * Method:    deleteNativeTimer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_ProtolibTimer_deleteNativeTimer
  (JNIEnv *, jobject);

/*
 * Class:     agentj_nativeimp_ProtolibTimer
 * Method:    cancelNativeTimer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_nativeimp_ProtolibTimer_cancelNativeTimer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
