/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_AgentJAgent */

#ifndef _Included_agentj_AgentJAgent
#define _Included_agentj_AgentJAgent
#ifdef __cplusplus
extern "C" {
#endif
#undef agentj_AgentJAgent_PL_FATAL
#define agentj_AgentJAgent_PL_FATAL 0L
#undef agentj_AgentJAgent_PL_ERROR
#define agentj_AgentJAgent_PL_ERROR 1L
#undef agentj_AgentJAgent_PL_WARN
#define agentj_AgentJAgent_PL_WARN 2L
#undef agentj_AgentJAgent_PL_INFO
#define agentj_AgentJAgent_PL_INFO 3L
#undef agentj_AgentJAgent_PL_DEBUG
#define agentj_AgentJAgent_PL_DEBUG 4L
#undef agentj_AgentJAgent_PL_TRACE
#define agentj_AgentJAgent_PL_TRACE 5L
#undef agentj_AgentJAgent_PL_DETAIL
#define agentj_AgentJAgent_PL_DETAIL 6L
#undef agentj_AgentJAgent_PL_MAX
#define agentj_AgentJAgent_PL_MAX 7L
/*
 * Class:     agentj_AgentJAgent
 * Method:    storeReference
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_AgentJAgent_storeReference
  (JNIEnv *, jobject);

/*
 * Class:     agentj_AgentJAgent
 * Method:    getAgentTCLName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_agentj_AgentJAgent_getAgentTCLName
  (JNIEnv *, jobject);

/*
 * Class:     agentj_AgentJAgent
 * Method:    getSystemTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_agentj_AgentJAgent_getSystemTime
  (JNIEnv *, jobject);

/*
 * Class:     agentj_AgentJAgent
 * Method:    tclEvaluateOnAgent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_agentj_AgentJAgent_tclEvaluateOnAgent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     agentj_AgentJAgent
 * Method:    tclEvaluateOnSimulator
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_agentj_AgentJAgent_tclEvaluateOnSimulator
  (JNIEnv *, jclass, jstring);

/*
 * Class:     agentj_AgentJAgent
 * Method:    tclEvaluate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_agentj_AgentJAgent_tclEvaluate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     agentj_AgentJAgent
 * Method:    setNativeDebugLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_agentj_AgentJAgent_setNativeDebugLevel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
