/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_AgentJAgent_AgentJDebugLevel */

#ifndef _Included_agentj_AgentJAgent_AgentJDebugLevel
#define _Included_agentj_AgentJAgent_AgentJDebugLevel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
