/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentj_Ns2MobileNode */

#ifndef _Included_agentj_Ns2MobileNode
#define _Included_agentj_Ns2MobileNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agentj_Ns2MobileNode
 * Method:    update_position
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentj_Ns2MobileNode_update_1position
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
